# Generated by Django 3.2 on 2021-05-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author'], 'permissions': (('can_delete_book', 'Can delete book'),)},
        ),
    ]
